<a href="https://colab.research.google.com/github/Tiamiyu1/Python-for-Data-Science-and-Analytics/blob/main/Classes/Day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Python Fundamentals


## 2. Python for Data Analytics

### Numpy
### Pandas

# Numpy

Meaning - import - alias

array np.array

Dimensions - 0,1,2, 3(matrices) - arr.ndim

Accessing - 1,2,3 d arrays [0,1]

np.arange(1,10), .reshape(3,3) / Generate random randint(start, stop, howmany), reshape

Indexing and slicing


Array operation - Elementwise/scaler +, -, *

Aggregation - max, min, max(axis=0)


Application - MSE (1/n*(np.sum(np.square(pred - true))))



In [1]:
import numpy as np

arr = np.array([1,3,5,6])
arr


array([1, 3, 5, 6])

In [2]:
type(arr)

numpy.ndarray

In [3]:
zero = np.array(67)

In [4]:
zero.ndim

0

In [5]:
one = np.array([34,56,23])

In [6]:
two = np.array([[2,45,67], [56,76,12]])

In [7]:
two.ndim

2

In [8]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
rr = np.array([45,2,3])

In [11]:
rr[2]

3

In [12]:
arr = np.array([[34,56,7], [89,9, 12]])
arr

array([[34, 56,  7],
       [89,  9, 12]])

In [13]:
arr = arr.reshape(3,2)

In [14]:
arr

array([[34, 56],
       [ 7, 89],
       [ 9, 12]])

In [15]:
arr[1,0]

7

In [16]:
arr[1]

array([ 7, 89])

In [17]:
arr[2]

array([ 9, 12])

In [18]:
arr[1:]

array([[ 7, 89],
       [ 9, 12]])

In [19]:
arr[0,]

array([34, 56])

In [20]:
arr

array([[34, 56],
       [ 7, 89],
       [ 9, 12]])

In [21]:
arr*2

array([[ 68, 112],
       [ 14, 178],
       [ 18,  24]])

In [22]:
arr+10

array([[44, 66],
       [17, 99],
       [19, 22]])

In [23]:
arr

array([[34, 56],
       [ 7, 89],
       [ 9, 12]])

In [24]:
arr.max()

89

In [25]:
arr.min()

7

In [26]:
arr.max(axis=1)

array([56, 89, 12])

In [27]:
arr.mean()

34.5

## Mean Absolute Error (MAE)

### MSE = (1/n)*(np.sum(np.square(pred - true)))

In [28]:
pred = np.array([23,45,67,78])
true = np.array([20,47,70,82])

In [29]:
(1/4)*np.sum(np.square(pred - true))

9.5

In [30]:
from sklearn.metrics import mean_squared_error
mean_squared_error(pred, true)

9.5

In [31]:
np.array([[1,2,3] ])

array([[1, 2, 3]])

In [32]:
arr1 = np.array(np.arange(1,7)).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2=arr1.reshape(3,2)
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
arr2[:,0]

array([1, 3, 5])

In [35]:
arr2[:,1]

array([2, 4, 6])

In [36]:
arr2[1:,1]

array([4, 6])

## Pandas